#include <stdio.h>
#include "pico/stdlib.h"
#include "pico/time.h"
#include "hardware/i2c.h"
#include "hardware/adc.h"
#include "ssd1306.h"
#include "font.h"

// I2C defines
#define I2C_PORT i2c0 //default
#define I2C_SDA 8 //GP08 on Raspberry Pi Pico
#define I2C_SCL 9 //GP09 on Raspberry Pi Pico 

// Heartbeat LED pin (on Raspberry Pi Pico)
#define HEARTBEAT_PIN 15  //GP15 on the Raspberry Pi Pico

//time variables for the frame per second values
absolute_time_t last_frame_time;
float fps = 0.0f;

void update_fps() {
    absolute_time_t now = get_absolute_time();
    int64_t delta_us = absolute_time_diff_us(last_frame_time, now);

    if (delta_us > 0) {
        fps = 1e6f / delta_us;  // frames per second (fps) = 1
    }

    last_frame_time = now;
}

void draw_fps() {
    char fps_str[50];
    sprintf(fps_str, "FPS: %.1f", fps);

    //draw fps at bottom-left corner (x=0, y=SCREEN_HEIGHT - CHAR_HEIGHT)
    drawMessage(0, 32-8, 1, fps_str);
}

int main() {
    stdio_init_all();

    //initialize I2C at 400 kHz
    i2c_init(I2C_PORT, 400 * 1000);
    gpio_set_function(I2C_SDA, GPIO_FUNC_I2C);
    gpio_set_function(I2C_SCL, GPIO_FUNC_I2C);
    gpio_pull_up(I2C_SDA);
    gpio_pull_up(I2C_SCL);

    sleep_ms(2000); //allow time for the system to initialize

    //initialize heartbeat LED (GP15)
    gpio_init(HEARTBEAT_PIN);
    gpio_set_dir(HEARTBEAT_PIN, GPIO_OUT);

    //initialize the ADC
    adc_init();
    adc_gpio_init(26);
    adc_select_input(0);
    

    //initialize SSD1306 OLED display
    ssd1306_setup();

    //clear the display buffer initially
    ssd1306_clear();

    //need current time for the fps 
    last_frame_time = get_absolute_time();


    bool pixel_on = false;

    while (true) {

        //heartbeat for the pico
        
        //turn on the heartbeat LED
        gpio_put(HEARTBEAT_PIN, 1);
        sleep_ms(500);  //wait 500 ms

        //turn off the heartbeat LED
        gpio_put(HEARTBEAT_PIN, 0);
        sleep_ms(500);  //wait 500 ms

        //toggle pixel state at 1 Hz (every second)
        pixel_on = !pixel_on;

        //TASK 1: using pixel 0,0 to flash at 1 Hz
        //ssd1306_drawPixel(0, 0, pixel_on ? 1 : 0);
        //update: successful

        //TASK 2: write a letter at a given position
        //drawChar(10, 10, 1, 'A');  // Draw 'A' at (10,10) in white
        //update: successful

        //TASK 3: write a function that prints a character array generated by sprintf() at a position
        // char message[50]; 
        // sprintf(message, "hello world"); 
        // drawMessage(5,5,1,message); // draw starting at x=5,y=5
        //update: successful 

        //TASK 4: write a program that prints the value of ADC0 in volts
        uint16_t raw = adc_read();
        float volts = raw * 3.3f / 4095.0f;
        char voltage[50];
        sprintf(voltage, "ADC0 voltage: %.3f", volts);
        drawMessage(5, 5 + 8, 1, voltage);

        //have to get fps to display at the bottom 
        update_fps();
        draw_fps();


        //update the OLED display to show changes
        ssd1306_update();
    }

    return 0;

}